# version: "3.8"

services:
  # ---------- MLflow Tracking Server ----------
  mlflow:
    image: ghcr.io/mlflow/mlflow:v3.9.0
    container_name: fraud-mlflow
    command: >
      mlflow server
      --host 0.0.0.0
      --port 5000
      --backend-store-uri sqlite:///mlflow/mlflow.db
      --allowed-hosts '*'
      --default-artifact-root /mlflow/artifacts
    ports:
      - "5001:5000"
    volumes:
      - mlflow_data:/mlflow

  # ---------- FastAPI Inference ----------
  api:
    build:
      context: .
      dockerfile: Dockerfile.infer
    container_name: fraud-api
    environment:
      # MLflow-first model loading (comment out MODEL_PATH to use MLflow)
      - MLFLOW_TRACKING_URI=http://mlflow:5000
      - MLFLOW_MODEL_NAME=fraud-model
      # - MLFLOW_MODEL_STAGE=Production
      # Local fallback (uncomment to bypass MLflow)
      # - MODEL_PATH=models/model_v1.joblib
      # - SCHEMA_PATH=models/model_v1_schema.json
      - MODEL_VERSION=v1
      - PRED_THRESHOLD=0.01
      - LOG_LEVEL=INFO
    ports:
      - "8001:8001"
    depends_on:
      - mlflow
    volumes:
      - mlflow_data:/mlflow 

  # --- Tourne 1 fois puis s'arrête ---
  train:
    build:
      context: .
      dockerfile: Dockerfile.train
    volumes:
      - ./data:/app/data        # Monte le dataset
      - ./models:/app/models    # Récupère le modèle local
      - mlflow_data:/mlflow 
    depends_on:
      - mlflow
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    profiles: ["train"]  # Ne démarre PAS par dqéfaut

  prometheus:
    image: prom/prometheus:v2.54.0
    container_name: fraud-prometheus
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9092:9090"
    depends_on:
      - api

  grafana:
    image: grafana/grafana:10.4.2
    container_name: fraud-grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin123
    ports:
      - "3002:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - prometheus

  # ---------- Streamlit UI ----------
  ui:
    build:
      context: .
      dockerfile: Dockerfile.ui
    container_name: fraud-ui
    environment:
      - API_URL=http://api:8001
      - MLFLOW_URL=http://mlflow:5000
    ports:
      - "8501:8501"
    depends_on:
      - api
    volumes:
      - ./data:/app/data

volumes:
  grafana_data:
  mlflow_data:




# docker compose --profile train up