services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      MLFLOW_TRACKING_URI: http://mlflow:5000
      REGISTERED_MODEL_NAME: CaliforniaHousingRF
      SCALER_ARTIFACT_PATH: preprocess/scaler.pkl
    depends_on:
      - mlflow

  mlflow:
    image: ghcr.io/mlflow/mlflow:latest
    ports:
      - "5050:5000"
    volumes:
      - ./mlruns:/app/mlruns
      - ./mlartifacts:/app/mlartifacts
    command: >
      mlflow server --host 0.0.0.0 --port 5000
      --backend-store-uri /app/mlruns
      --artifacts-destination /app/mlartifacts
      --serve-artifacts
      --allowed-hosts "*"

      